apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"homeverse-service","namespace":"default"},"spec":{"ports":[{"port":80,"targetPort":80}],"selector":{"app":"homeverse"},"type":"LoadBalancer"}}
  creationTimestamp: "2025-04-06T13:43:32Z"
  name: homeverse-service
  namespace: default
  resourceVersion: "1150"
  uid: 21368420-2da0-44dd-ad9f-2de411326de6
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.106.27.138
  clusterIPs:
  - 10.106.27.138
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32141
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: homeverse
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
