apiVersion: v1
kind: Service
metadata:
  name: homeverse-service
  labels:
    app: homeverse
spec:
  selector:
    app: homeverse
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
  type: NodePort
