apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"homeverse"},"name":"homeverse-deployment","namespace":"default"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"homeverse"}},"template":{"metadata":{"labels":{"app":"homeverse"}},"spec":{"containers":[{"image":"homeverse-app:v1","imagePullPolicy":"Never","name":"homeverse","ports":[{"containerPort":80}],"resources":{"limits":{"cpu":"500m","memory":"512Mi"},"requests":{"cpu":"200m","memory":"256Mi"}}}]}}}}
  creationTimestamp: "2025-04-06T13:54:10Z"
  generation: 1
  labels:
    app: homeverse
  name: homeverse-deployment
  namespace: default
  resourceVersion: "2583"
  uid: f3b033af-7c3c-4964-99cd-857c1a73898c
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: homeverse
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: homeverse
    spec:
      containers:
      - image: homeverse-app:v1
        imagePullPolicy: Never
        name: homeverse
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2025-04-06T13:54:10Z"
    lastUpdateTime: "2025-04-06T13:56:06Z"
    message: ReplicaSet "homeverse-deployment-5d86df46d9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-04-06T13:56:59Z"
    lastUpdateTime: "2025-04-06T13:56:59Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
